Repository yt-project/yt_idv, pull requests merged in 2024-12, with the labels that each got.

#158 add a note on why ratio is needed in BlockCollection.add_data
  yt_idv/scene_data/block_collection.py
Labels: documentation

#162 fix extras deprecation warning
  yt_idv/tests/test_yt_idv.py
Labels: infrastructure

#89 preprocessor directives followup
  yt_idv/scene_components/base_component.py
  yt_idv/shader_objects.py
  yt_idv/shaders/apply_colormap.frag.glsl
  yt_idv/shaders/known_uniforms.inc.glsl
  yt_idv/tests/test_preprocessor_state.py
  yt_idv/tests/test_yt_idv.py
Labels: enhancement

#137 Multiple views in a single window
  examples/multiview_rendering.py
  yt_idv/rendering_contexts/pyglet_context.py
  yt_idv/scene_components/base_component.py
  yt_idv/shaders/display_border.frag.glsl
  yt_idv/shaders/known_uniforms.inc.glsl
  yt_idv/shaders/shaderlist.yaml
Labels: enhancement

#156 Add some camera adjustments
  yt_idv/cameras/base_camera.py
  yt_idv/rendering_contexts/pyglet_context.py
  yt_idv/simple_gui.py
Labels: enhancement
